<?php

$title = 'Test Form';
/** @var Zend\View\Renderer\PhpRenderer $this */
$this->headTitle($title);
// within a view script
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Get the form label plugin
$formLabel = $this->plugin('formLabel');
?>
<div class="container">
    <div class="panel">


        <?php
        // Render the opening tag

        echo $this->form()->openTag($form);
        ?>
        <div class="form_element form-group">
            <?php
            $name = $form->get('account');
            //$name->setAttribute('class', 'form-control');
            echo $formLabel->openTag() . $name->getOption('label');
            echo $this->formInput($name);
            echo $this->formElementErrors($name);
            echo $formLabel->closeTag();
            ?>
        </div>

        <div class="form_element form-group">
            <?php
            $subject = $form->get('password');
            echo $formLabel->openTag() . $subject->getOption('label');
            echo $this->formPassword($subject);
            echo $this->formElementErrors($subject);
            echo $formLabel->closeTag();
            ?>
        </div>

        <div class="form_element form-group">
            <?php
            $captcha = $form->get('captcha');
            echo $formLabel->openTag() . $captcha->getOption('label');
            echo $formLabel->closeTag();
            ?>
            <br>
            <?php
            /** @var \Zend\Form\View\Helper\Captcha\Image $helper */
            $helper = $this->plugin($captcha->getCaptcha()->getHelperName());

            $helper->setCaptchaPosition(\Zend\Form\View\Helper\Captcha\AbstractWord::CAPTCHA_PREPEND);
            //$helper->setSeparator('<span class="input-group-addon">');
            echo $helper($captcha);
            //echo $this->formCaptcha();
            ?>

            <?php
            echo $this->formElementErrors($captcha);

            ?>
        </div>

        <?php echo $this->formElement($form->get('security')) ?>
        <?php echo $this->formElement($form->get('send')) ?>

        <?php echo $this->form()->closeTag() ?>

    </div>
</div>
<style>
#login-captcha{
    display: inline;
    width: 100px;
}
</style>