<div>
    <input id="file" type="file">
</div>
<script>
    $(function(){
        $("#file").change(function(){
            if(this.files.length > 0)
            {
                FileUpload.sendFile(
                    '',
                    this.files[0],
                    {},
                    function(){

                    }
                );
            }
        });
    })
</script>
