<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Title - ZF2 测试</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="/kendoui/styles/kendo.default.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/kendoui/styles/kendo.common.min.css" media="screen" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/kendoui/js/jquery.min.js"></script>
    <script type="text/javascript" src="/kendoui/js/kendo.all.min.js"></script>
    <script type="text/javascript" src="/js/formCreator.js"></script>

</head>
<body style="display: block; margin: 0; padding: 0; min-height: 100%;">
<?php echo $this->content; ?>
</body>
</html>
<style>
    html, body{
        height: 100%;
    }
</style>