<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
$this->headTitle("Title");
?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('测试'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/kendoui/styles/kendo.common.min.css')
                        ->prependStylesheet($this->basePath() . '/kendoui/styles/kendo.default.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')

            ->prependFile($this->basePath() . '/kendoui/js/kendo.all.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/formCreator.js')
            ->prependFile($this->basePath() . '/js/FileUpload.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js');
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('test') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('测试') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setMaxDepth(0)->setMinDepth(0)->setUlClass('nav navbar-nav'); ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">

            <?php echo $this->content; ?>
            <?php
                /** @var Zend\View\Helper\HeadTitle $headTitle */
                $headTitle = $this->headTitle();
                echo $headTitle->toString();
            ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
